### ISSUE TITLE
400 BadRequest on uploading "collection of bytes"

### ISSUE THREAD

**Issue by sirocchj** [Trulioo/sdk-java-v1#4]
POSTing a verification request containing "images" (as per sample in https://github.com/Trulioo/sdk-java-v1/blob/master/sample/SdkJavaV1Sample.java#L85) is producing a `400 BadRequest`.

Details in the response:
```
{"Message":"The request is invalid.","ModelState":{"request.DocumentFrontImage[0]":["An error has occurred."],"request.DocumentBackImage[0]":["An error has occurred."]}}
```

**Comment by dbraaten42** [comment]
Hi sirocchj,

The best thing to do is open a ticket with customer support.  They can make sure your account is configured for document verification and that everything is good on our end.  They will also be able to collect details about your transactions in a secure manner.  

If your account is setup correctly make sure your images are under 3MB.  

Darryl

**Comment by dbraaten42** [comment]
This issue should now be resolved.
